workflows:
  android-ci:
    name: Android CI
    max_build_duration: 60
    environment:
      vars:
        VERSION_NAME: $(date +'%Y.%m.%d')
        VERSION_CODE: $CM_BUILD_ID
        GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx4096m
      java: 21
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        - ~/.android/build-cache
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'master'
          include: true
    scripts:
      - name: Checkout project
        script: |
          echo "🔄 Checking out project..."
          git clone $CM_REPO_CLONE_URL .
      - name: Prepare Gradle
        script: |
          echo "⚙️ Setting up Gradle wrapper..."
          chmod +x gradlew
      - name: Validate Gradle Wrapper
        script: |
          ./gradlew wrapper --gradle-version 8.9
      - name: Build Release APK
        script: |
          echo "🚀 Building release APK..."
          ./gradlew clean assembleRelease
      - name: List output files
        script: |
          echo "📦 Output APKs:"
          ls -lh app/build/outputs/apk/release/
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - $CM_USER_EMAIL
        notify:
          success: true
          failure: true
